// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUmIpZfbr2_3TidEk6tJ8gfpQKi9eOlgg',
    appId: '1:448412086169:web:094b3d1d9e908c2c62ed08',
    messagingSenderId: '448412086169',
    projectId: 'chatosmessenger-525c4',
    authDomain: 'chatosmessenger-525c4.firebaseapp.com',
    storageBucket: 'chatosmessenger-525c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_0vjogT4GTzJDqg9a-RJgJ7S8C17k3Y',
    appId: '1:448412086169:android:9d9bbc1c2eed7d2e62ed08',
    messagingSenderId: '448412086169',
    projectId: 'chatosmessenger-525c4',
    storageBucket: 'chatosmessenger-525c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2W0OEIzUaizuO_oNepvXx0nqndfLRSA0',
    appId: '1:448412086169:ios:070e8e915b8adade62ed08',
    messagingSenderId: '448412086169',
    projectId: 'chatosmessenger-525c4',
    storageBucket: 'chatosmessenger-525c4.appspot.com',
    iosBundleId: 'com.example.chatosMessenger',
  );
}
